#!/bin/bash

# clean up
rm *.sls *.slg *.slo *.gls *.ist *.glg *.glo *.alg *.acr *.acn *.aux *.auxlock *.bbl *.bcf *.blg *.log *.out *.run.xml *.sta *.spl *.len *.nav *.snm *.toc *.pag *.glsdefs example03.pdf 2>>/dev/null

pdflatex example03
biber example03
pdflatex example03
pdflatex example03

# clean up
rm *.sls *.slg *.slo *.gls *.ist *.glg *.glo *.alg *.acr *.acn *.aux *.auxlock *.bbl *.bcf *.blg *.log *.out *.run.xml *.sta *.spl *.len *.nav *.snm *.toc *.pag *.glsdefs 2>>/dev/null
